name: Setup Node
description: Setups latest Node LTS and installs dependencies

runs:
  using: composite
  steps:
    - name: Detect Node Package Manager
      id: detect-node-pm
      run: |
        if [ -f "yarn.lock" ]; then
          if [ -d ".yarn" ]; then
            echo "node-pm=yarn2" >> $GITHUB_OUTPUT
          else
            echo "node-pm=yarn1" >> $GITHUB_OUTPUT
          fi
        elif [ -f "pnpm-lock.yaml" ]; then
          echo "node-pm=pnpm" >> $GITHUB_OUTPUT
        else
          echo "node-pm=npm" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Display Node Package Manager
      run: 'echo Package Manager: ${{ steps.detect-node-pm.outputs.node-pm }}'
      shell: bash
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: ${{ steps.detect-node-pm.outputs.node-pm }}
        check-latest: true
        node-version: 16
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      id: node-modules-cache
      with:
        path: |
          node_modules
          .yarn
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
    - name: Install Dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: |
        if [ $PM == "yarn1" ]; then
          yarn install --frozen-lockfile
        elif [ $PM == "yarn" ]; then
          yarn --immutable
        elif [ $PM == "pnpm" ]; then
          pnpm install --frozen-lockfile
        else
          npm ci
        fi
      shell: bash
      env:
        PM: ${{ steps.detect-node-pm.outputs.node-pm }}
