---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /
    requirements-file: requirements-dev.txt
    schedule:
      interval: daily
