repository:
  name: .github
  description: Default files for all my repositories
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  delete_branch_on_merge: true
  has_projects: false
  has_wiki: false
  squash_merge_commit_title: COMMIT_OR_PR_TITLE
  topics: github, github-config, defaults, default-files
  homepage: https://fernandopasik.com
