# Repository settings https://docs.github.com/en/rest/repos/repos#update-a-repository
repository:
  name: .github
  description: Default files for all my repositories
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  delete_branch_on_merge: true
  has_projects: false
  has_wiki: false
  security_and_analysis:
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled
  squash_merge_commit_title: COMMIT_OR_PR_TITLE
  topics: github, github-config, defaults, default-files
  homepage: https://fernandopasik.com
