---
# Configuration for probot-stale - https://github.com/probot/stale

closeComment: false

daysUntilClose: 7
daysUntilStale: 30

exemptLabels:
  - wip
  - help wanted

markComment: >
  This issue has been automatically marked as stale because it has not had recent activity.
  It will be closed if no further activity occurs. Thank you for your contributions.
