name: Setup
description: Setups latest Node LTS and installs dependencies

runs:
  using: composite
  steps:
    - id: detect-node-pm
      uses: ./.github/actions/detect-node-pm
    - name: Output result
      run: echo ${{ steps.detect-node-pm.outputs.node-pm }}
      shell: bash
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache: npm
        check-latest: true
        node-version: 16
    - name: Install Dependencies
      run: npm ci
      shell: bash
