name: Detect Node Package Manager
description: Check which node package manager is used by the project

outputs:
  node-pm:
    description: Node Package Manager
    value: ${{ steps.detect-node-pm.outputs.node-pm }}

runs:
  using: composite
  steps:
    - id: detect-node-pm
      name: Detect Node Package Manager
      run: |
        if [ -f "yarn.lock" ]; then
          if [ -d ".yarn" ]; then
            echo "node-pm=yarn2" >> $GITHUB_OUTPUT
          else
            echo "node-pm=yarn1" >> $GITHUB_OUTPUT
          fi
        elif [ -f "pnpm-lock.yaml" ]; then
          echo "node-pm=pnpm" >> $GITHUB_OUTPUT
        else
          echo "node-pm=npm" >> $GITHUB_OUTPUT
        fi
      shell: bash
