name: Setup Python
description: Setups latest Python and installs dependencies

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        check-latest: true
        python-version: 3.x
    - uses: actions/cache@v3
      id: python-cache
      with:
        path: |
          venv
        key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/*requirements.txt') }}
    - name: Install Python Dependencies
      if: steps.python-cache.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
      shell: bash
