---
name: main
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  install-node:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
  install-python:
    name: Install Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: fernandopasik/actions/setup-python@main
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    needs: install-node
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: fernandopasik/actions/setup-node@main
      - name: Check Format
        run: npm run format:check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install-python
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: ./setup-python
      - name: Lint
        run: yamllint .
