name: Setup Node
on:
  workflow_call:

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  show-version:
    name: Display Node version
    runs-on: ubuntu-latest
    steps:
      - name: Display Node version
        run: node -v
